### ISSUE TITLE
Routing strategy seems to break due to router entering an infinite loop when noAuthGuard is doing an async operation

### ISSUE THREAD

**Issue by juanmesa2097** [juanmesa2097/angular-boilerplate#139]
@juanmesa2097 routing strategy seems to break due to router entering an infinite loop when noAuthGuard is doing an async operation, for example rather checking whats in the subject on load- what if we want the page to survive page refreshes by checking a session on the server.. sync operations seems to work fine but not async

```
const test = () => {
  return new Promise((res, rej) => {
    setTimeout(() => {
      res(true);
    });
  });
};

async canActivate() {
  const isLoggedIn = await test();
    if (isLoggedIn) {
      this.router.navigate([Path.App]);
      return false;
    }
    return true;
}
```

_Originally posted by @s1eeper888 in https://github.com/juanmesa2097/angular-boilerplate/issues/121#issuecomment-772519375_

**Comment by juanmesa2097** [comment]
@s1eeper888 for async operations you can return a promise or an observable. Since you need to handle a side effect which is to redirect the user if is logged in, I think the best choice is to convert the promise into an observable and use the tap operator to handle side effects.

```ts
const test = (): Promise<boolean> => {
  return new Promise((res, rej) => {
    setTimeout(() => {
      res(true);
    }, 3000);
  });
};

canActivate(
    next: ActivatedRouteSnapshot,
    state: RouterStateSnapshot
  ):
    | Observable<boolean | UrlTree>
    | Promise<boolean | UrlTree>
    | boolean
    | UrlTree {
    return from(test()).pipe(
      tap((isLoggedIn) => {
        if (isLoggedIn) {
          this.router.navigate([Path.App]);
        }
      })
    );
  }
```

Please, let me know if this works for you.

**Comment by s1eeper888** [comment]
@juanmesa2097 doh.. man I did not have my coffee this morning! hehe. Thanks @juanmesa2097

**Comment by juanmesa2097** [comment]
@s1eeper888 haha anytime.
