### ISSUE TITLE
Build fail: Peer dependency issue with mini-css-extract-plugin and postcss-loader

### ISSUE THREAD

**Issue by akumar3pimco** [juanmesa2097/angular-boilerplate#164]
System specification: 
Angular CLI: 11.1.4
Node: 14.4.0
OS: win32 x64

Angular: 11.0.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.4
@angular-devkit/build-angular   0.1101.4
@angular-devkit/core            11.1.4
@angular-devkit/schematics      11.1.4
@angular/cli                    11.1.4
@angular/localize               11.2.0
@schematics/angular             11.1.4
@schematics/update              0.1101.4
rxjs                            6.6.3
typescript                      4.0.7

Getting below error when I run npm start, even I have install all the peer dependency manually.

Error: ./src/css/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (C:\Arvind\learnings\angular-boilerplate-main\angular-boilerplate-main\node_modules\postcss-loader\dist\index.js:38:24)
    at C:\Arvind\learnings\angular-boilerplate-main\angular-boilerplate-main\node_modules\webpack\lib\NormalModule.js:316:20
    at C:\Arvind\learnings\angular-boilerplate-main\angular-boilerplate-main\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Arvind\learnings\angular-boilerplate-main\angular-boilerplate-main\node_modules\loader-runner\lib\LoaderRunner.js:233:18

Error: ./src/app/@components/header/header.component.scss
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (C:\Arvind\learnings\angular-boilerplate-main\angular-boilerplate-main\node_modules\postcss-loader\dist\index.js:38:24)

**Comment by juanmesa2097** [comment]
Hi @akumar3pimco,

Angular includes native support for TailwindCSS in this new version v11.2 https://twitter.com/angular/status/1359736376581840896

I'm already working on this: we'll go back to `@angular-devkit/build-angular` from `@angular-builders/custom-webpack`.

The code will be refactored & cleaned up. I'll push the changes in the next hours.
