### ISSUE TITLE
Implement a spinner during auth

### ISSUE THREAD

**Issue by s1eeper888** [juanmesa2097/angular-boilerplate#171]
**Is your feature request related to a problem? Please describe.**
When we are authenticating/unauthenticating asynchronously and leveraging subjects to destroy different router outlets there seems to be some stuttering happening. When transitioning from the first sign in -> feature pages. However, this doesn't happen if we are on the same session where we log out and relogin.

**Describe the solution you'd like**
For example: we authenteciate.. and await the response.. then once we are authenticated.. we emit true to the login subject... << router outlet is empty at this point >> since the router could potentially still be fetching the first lazyloaded chunk... Maybe we can present some sort of loader thats being monitor via RouteConfig router events or some sort.

**Comment by juanmesa2097** [comment]
I think we can implement this. There are lots of ways of doing that. I think the most generic one would be creating a self-contained module (like the ones in [here](https://github.com/juanmesa2097/angular-boilerplate/tree/main/src/app/%40components)) & use [TailwindCSS animations](https://tailwindcss.com/docs/animation) to keep it standard, that way, we could reuse it on every module & not just in Auth.  We could also use different sizes for the spinner (xs, sm, base, lg, xl) and it could be attached to a container or it could cover the whole screen. The visibility could be controlled by an input or by a generic service using observables for each request.

Let me know what you think & if you'd like to submit a PR.

**Comment by s1eeper888** [comment]
@juanmesa2097 will work on this when I have time, its on my todo list :)

**Comment by juanmesa2097** [comment]
@s1eeper888 Thank you

**Comment by juanmesa2097** [comment]
Closed since non-essential components will be removed in favor of [a fully-featured template](https://github.com/juanmesa2097/ngx-admin-template)

**Comment by SavageCore** [comment]
> Closed since non-essential components will be removed in favor of [a fully-featured template](https://github.com/juanmesa2097/ngx-admin-template)

What happened to this repo? It sounds like a great idea!

**Comment by juanmesa2097** [comment]
> > Closed since non-essential components will be removed in favor of [a fully-featured template](https://github.com/juanmesa2097/ngx-admin-template)
> 
> What happened to this repo? It sounds like a great idea!

I'll start with this in the next incoming weeks after I finish some work since it is a big & customizable project but be sure that this will be implemented and it's going to be amazing.
