### ISSUE TITLE
Cypress - add "@briebug/cypress-schematic"

### ISSUE THREAD

**Issue by pehleme** [juanmesa2097/angular-boilerplate#311]
Need add "@briebug/cypress-schematic" to run Cypress

`npm run test:e2e`

![image](https://user-images.githubusercontent.com/32654571/116510316-1d4e4c80-a89b-11eb-8331-eac03a48f473.png)

**Comment by juanmesa2097** [comment]
@pehleme thank you very much for opening this. Will check it out!

**Comment by juanmesa2097** [comment]
This error is fixed but there seems to be an issue with the schematic https://github.com/briebug/cypress-schematic/issues/103
