### ISSUE TITLE
npm install doesn't work

### ISSUE THREAD

**Issue by rballonline** [juanmesa2097/angular-boilerplate#580]
**Describe the bug**
Can't git clone and npm install the project

**To Reproduce**
1. git clone https://github.com/juanmesa2097/angular-boilerplate.git
2. npm install

**Expected behavior**
npm would finish installing without errors

**Output**
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: angular-boilerplate@0.0.0
npm ERR! Found: rxjs@7.1.0
npm ERR! node_modules/rxjs
npm ERR!   rxjs@"7.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"^6.5.3" from @angular/core@12.0.1
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"12.0.1" from the root project
npm ERR!   peer @angular/core@"12.0.1" from @angular/animations@12.0.1
npm ERR!   node_modules/@angular/animations
npm ERR!     @angular/animations@"12.0.1" from the root project

**System info:**
Angular CLI: 12.2.7
Node: 14.17.1
Package Manager: npm 7.21.0
OS: win32 x64

**Comment by juanmesa2097** [comment]
Thanks for reporting!
