### ISSUE TITLE
How to create a page using command line. Every time on ng g c <c-name> generates a component. How to generate a page using command line.

### ISSUE THREAD

**Issue by deepakbawaorion** [juanmesa2097/angular-boilerplate#604]
How to create a page using command line. Every time on ng g c <c-name> generates a component. How to generate a page using command line. As in your boiler plate docs I did not find any tutorial to create a page. Or you need to describe how one can create pages in your boiler plate.

**Comment by juanmesa2097** [comment]
You can use the [type option](https://angular.io/cli/generate#component) to generate components with the suffix "page"

```console
ng g c component --type=page
```
