### ISSUE TITLE
Import of module is not needed when it has been already imported in another module

### ISSUE THREAD

**Issue by sagarguhe** [juanmesa2097/angular-boilerplate#605]
**Describe the bug**
Not exactly a bug but when we are following SCAM pattern, why to import and export a module again just above a module which has already imported it.

**To Reproduce**
`WebShellModule` (web-shell.module.ts) has imported `HeaderModule` and `FooterModule` which `LayoutModule` has already imported.

**Expected behavior**
I think import of `HeaderModule` and `FooterModule` is not needed here because without import of both these modules applications works.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sagarguhe** [comment]
May be there is another reason for doing this that I am not aware of (or may be this is how it works, I am new to Angular/SCAM)

**Comment by juanmesa2097** [comment]
@sagarguhe thanks for noticing. You're totally right, the import and export of the Header and Footer modules are unnecessary and I've missed that. Do you want to submit a PR?
