### ISSUE TITLE
Custom directive problem

### ISSUE THREAD

**Issue by naipli** [juanmesa2097/angular-boilerplate#606]
I couldn't run custom directive. What do I need to do to get it working.
![test-1](https://user-images.githubusercontent.com/55943439/173235017-ad5804a5-5959-4ea6-8340-b383a74b5763.PNG)
![test-4](https://user-images.githubusercontent.com/55943439/173235023-60645dfb-b64a-4f86-8d97-9fb2f2e0cf14.PNG)
![test-2](https://user-images.githubusercontent.com/55943439/173235019-d44df045-f988-49e0-95bd-42497bfffec6.PNG)
![test-3](https://user-images.githubusercontent.com/55943439/173235021-727bde09-d110-420a-93c5-171ae5108e60.PNG)
![image](https://user-images.githubusercontent.com/55943439/173235094-0d60949d-0d2a-4fc7-b33c-1430a0c93b27.png)

**Comment by juanmesa2097** [comment]
@naipli You're globally importing `CustomModule` in the `CoreModule`, but the feature modules of this project are lazy-loaded. You should import `CustomModule` in the feature module you want to use the directive (SettingsModule, TodosModule, etc.).

**Comment by naipli** [comment]
It worked. Thank you so much.

**Comment by juanmesa2097** [comment]
@naipli you're very welcome

**Comment by TANIAX** [comment]
Nvm I found the solution by reading [this article ]( https://levelup.gitconnected.com/angular-required-roles-directive-48f477f69d23)

Thanks anyway.
