### ISSUE TITLE
Adding interfaces and enums to libs folder

### ISSUE THREAD

**Issue by Mahmoudibrahim03** [juanmesa2097/angular-boilerplate#613]
**Is your feature request related to a problem? Please describe.**
 - no it didn't relate to any problem but I think it will be a great feature 

**Describe the solution you'd like**
- adding interfaces and enums section that will be used in common places like user interface and user role enum 

**Describe alternatives you've considered**
- I think alternatives will be to not use any of them but I feel like there is some stuff missing so the first thing I do when starting a new project is to create new sections for both of them to use TS power that we need 

**Additional context**
- I added a [PR](https://github.com/juanmesa2097/angular-boilerplate/pull/612) that helps to solve or add this feature to the repo so please feel free to contact or discuss it

**Comment by Mahmoudibrahim03** [comment]
@juanmesa2097 should I send you the PR link ?! 
https://github.com/juanmesa2097/angular-boilerplate/pull/612

**Comment by juanmesa2097** [comment]
@Mahmoudibrahim03 I left some comments in the PR about some things that should be modified. Did you see them?

**Comment by Mahmoudibrahim03** [comment]
> @Mahmoudibrahim03 I left some comments in the PR about some things that should be modified. Did you see them?

@juanmesa2097 
Sorry but I can't find any comments in the PR can you clarify to me where can I find these comments

**Comment by juanmesa2097** [comment]
> > @Mahmoudibrahim03 I left some comments in the PR about some things that should be modified. Did you see them?
> 
> @juanmesa2097 Sorry but I can't find any comments in the PR can you clarify to me where can I find these comments

Sure, take a look at the conversation tab
![image](https://user-images.githubusercontent.com/64181348/186545136-cadf1b88-a5bf-4e5d-8617-c309a4d2396d.png)
---
![image](https://user-images.githubusercontent.com/64181348/186545228-f247ccca-06bf-4cb6-9ff1-600075ca96c7.png)

**Comment by juanmesa2097** [comment]
@Mahmoudibrahim03 my bad, I didn't review it. Sorry

**Comment by Mahmoudibrahim03** [comment]
It's ok take your time @juanmesa2097

**Comment by Mahmoudibrahim03** [comment]
Ok, I have resolved the code review comments and pushed a new commit with the fixes @juanmesa2097

**Comment by juanmesa2097** [comment]
@Mahmoudibrahim03 great! the only thing missing is the "r" in the filename `use-role.enum.ts`

**Comment by Mahmoudibrahim03** [comment]
I got it @juanmesa2097

**Comment by juanmesa2097** [comment]
@Mahmoudibrahim03 thank you!
