### ISSUE TITLE
Interceptor issue 

### ISSUE THREAD

**Issue by hussambawwab** [juanmesa2097/angular-boilerplate#618]
Interceptor  dose not working in this project  structure

**Comment by Mahmoudibrahim03** [comment]
which one please !?

**Comment by hussambawwab** [comment]
both

**Comment by Mahmoudibrahim03** [comment]
ok let me doublecheck

**Comment by hussambawwab** [comment]
take your time , thank you .

**Comment by Mahmoudibrahim03** [comment]
@hussambawwab  I just have tested both and It works, as usual , so please attach a screenshot and env configuration you work on 

<img width="557" alt="Screenshot 2022-09-25 at 10 11 31 PM" src="https://user-images.githubusercontent.com/16546001/192163274-5797f56e-c2ea-42fe-af5a-0fd22153e373.png">
<img width="744" alt="Screenshot 2022-09-25 at 10 11 19 PM" src="https://user-images.githubusercontent.com/16546001/192163276-ef091fcb-5f72-4e22-9ef9-6119ef119139.png">
<img width="846" alt="Screenshot 2022-09-25 at 10 11 08 PM" src="https://user-images.githubusercontent.com/16546001/192163277-a16fdaa3-c13a-4042-8f4f-b77b3321feb8.png">

**Comment by hussambawwab** [comment]
![image](https://user-images.githubusercontent.com/44412043/192163620-e5eb9534-1289-4086-848b-51d3736bbba1.png)

this is the interceptor 

![image](https://user-images.githubusercontent.com/44412043/192163712-58428d49-9815-429e-9020-e530757394ac.png)

![image](https://user-images.githubusercontent.com/44412043/192163732-3ca6bb97-e0d0-486c-b6f5-6c35f02d0836.png)
 as you see there is nothing displays in console

**Comment by hussambawwab** [comment]
![image](https://user-images.githubusercontent.com/44412043/192164424-08e660b8-42b7-4774-9011-1c2c3c2681a3.png)
![image](https://user-images.githubusercontent.com/44412043/192164435-0ad50505-d44b-459c-9ab1-1e25e7e84c1c.png)
![image](https://user-images.githubusercontent.com/44412043/192164444-7a9b4585-ded1-484d-85cb-f6be78449e64.png)
![image](https://user-images.githubusercontent.com/44412043/192164457-55dac31e-b3bb-4647-9c73-9835efb300d0.png)
and here without doing any changes as is as original

**Comment by Mahmoudibrahim03** [comment]
try to comment on the second importProvider and check if the issue still exist

**Comment by hussambawwab** [comment]
unfortunately the issue is still happening after coment firebase import line

**Comment by hussambawwab** [comment]
as you said before the issue was in firebase line .
Thank you
